<a href="https://colab.research.google.com/github/yellayujin/studying/blob/main/240214_ML1(Pycaret%2C_lambda%2C_StratifiedKfold).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pycaret
pycaret.__version__

'3.2.0'

In [ ]:
import lightgbm
lightgbm.__version__

'4.3.0'

# Pycaret 사용해보기!
- 각 모델 비교해주는 부분까지만 보고(상세 생략 건너뜀), 나머지는 아래 링크로
- https://colab.research.google.com/github/pycaret/pycaret/blob/master/tutorials/Tutorial%20-%20Multiclass%20Classification.ipynb#scrollTo=0ec7fad6


In [ ]:
# loading sample dataset from pycaret dataset module
from pycaret.datasets import get_data
data = get_data('iris')

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
# import pycaret classification and init setup
from pycaret.classification import *
s = setup(data, target = 'species', session_id = 123)

In [ ]:
# import ClassificationExperiment and init the class
from pycaret.classification import ClassificationExperiment
exp = ClassificationExperiment()

In [ ]:
# check the type of exp
type(exp)

pycaret.classification.oop.ClassificationExperiment

In [ ]:
# init setup on exp
exp.setup(data, target = 'species', session_id = 123)

In [ ]:
# compare baseline models
best = compare_models()

In [ ]:
# compare models using OOP
exp.compare_models()

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Pandas 복습
- 구글 코랩의 경우 구글 코랩 연동
- from google.colab import drive
- drive.mount("/content/drive")

In [ ]:
import pandas as pd
data = pd.read_csv('./data/titanic_train.csv')
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
data['Embarked'] = data['Embarked'].fillna('S')
data['Embarked'].value_counts(dropna=False)

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [ ]:
data['Embarked'].value_counts(dropna=False).idxmax()

'S'

In [ ]:
data['Embarked'].mode()[0]

'S'

## 데이터 정의서
- 프로젝트시 각 데이터는 우리가 모아온 것이므로 데이터 정의서(친절한 코드북 느낌) 작성해야.
- kaggle 등에 예시 많음

## apply lambda 식으로 데이터 가공
- 일회성 사용자 정의 함수

### apply()
- 행 단위로 연산을 할 때, apply() 사용
    + lambda: 간단한 연산 할 때
    + udf(사용자 정의 함수): if 조건절이 여러 번 사용될 것 같은 상황이면 이게 나음

In [ ]:
def get_square(a):
    return a ** 2

get_square(8)

64

In [ ]:
lambda_square = lambda x: x ** 2
lambda_square(3)

9

In [ ]:
a = [1, 2, 3, 4, 5, 6]
squares = map(lambda x: x ** 2, a)
list(squares)

[1, 4, 9, 16, 25, 36]

In [ ]:
data['Name_len'] = data['Name'].apply(lambda x : len(x))   # 행 단위로 처리됨!!
data['Name_len']

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name_len, Length: 891, dtype: int64

In [ ]:
def get_category(age):
    cat = ''
    if age <= 5: cat = 'Baby'
    elif age <= 12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age <= 25: cat = 'Student'
    elif age <= 35: cat = 'Young Adult'
    elif age <= 60: cat = 'Adult'
    else : cat = 'Elderly'

    return cat

In [ ]:
# lambda에서는 else if 없음. 괄호로 넣어줘야하는데 여러 번 중첩되면 복잡해짐

## 사이킷런(Scikit-Learn)
- 파이썬 머신러닝 라이브러리
- 엑셀 데이터 -> 정형 데이터 -> 머신러닝 디폴트 라이브러리
    + 텐서플로, 케라스, 파이토치 등의 딥러닝 전문 라이브러리(비정형 데이터에 적합. 사이킷 런 잘 쓰진 않음)
    + 따라서 내가 풀어야 할 문제의 데이터가 정형인지 비정형인지 구분해야
- 파이썬 기반의 다른 머신러닝 패키지도 사이킷런 스타일의 API를 지향함
    + XGBoost, LightGBM, CatBoost 등의 알고리즘은 사이킷런 라이브러리 알고리즘 아님. 아예 별개.
    + 하지만 이들도 사이킷런 클래스처럼 사용이 가능하도록 지원
- 단점: GPU 연산을 못함 (CPU 연산만 함)

In [ ]:
import sklearn
sklearn.__version__

'1.2.2'

### 붓꽃 품종 예측하기

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [ ]:
# 데이터 프레임 만들기
iris = load_iris()
# iris   # 넘파이 배열

# 독립변수 = 설명변수
iris_data = iris.data  # 딕셔너리의 key값 중 data의 내용만 출력
# iris_data

# 종속변수
iris_label = iris.target  # 딕셔너리의 key값 중 target의 내용만 출력
# iris_label

In [ ]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
iris.target_names
# 0은 setosa, 1은 versicolor, 2는 virginica

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)  # 독립 변수의 컬럼 명을 feature_names라고 많이 씀
iris_df['label'] = iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [ ]:
# train, test로 분리(데이터가 작으니까)
iris_df.shape

# iris_data: 독립 데이터
# iris_label: 종속 데이터
# iris_df: 합친 것
X_tr, X_te, y_tr, y_te = train_test_split(iris_data, iris_label, test_size = 0.3, stratify = iris_label, random_state = 0)

# train_test_split 메서드는 일반적으로 X와 y 분리하고 사용함.

In [ ]:
# 훈련 데이터로 모델 학습하기(DecisionTreeClassifier)
dtc = DecisionTreeClassifier(random_state = 0)   # criterion='gini', max_depth=None 등의 옵션 있음
dtc.fit(X_tr, y_tr)  # 훈련 데이터 학습시키기

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=0, splitter='best')

In [ ]:
# 테스트 데이터로 예측하기
y_te_pred = dtc.predict(X_te)

In [ ]:
# 예측 성능 확인
 # 정확도 계산
from sklearn.metrics import accuracy_score
accuracy_score(y_te, y_te_pred)

0.9777777777777777

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
 # 혼동행렬 계산
print(confusion_matrix(y_te, y_te_pred))
 # classification_report 계산
print(classification_report(y_te, y_te_pred))

[[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.94      1.00      0.97        15
           2       1.00      0.93      0.97        15

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [ ]:
X_tr1, X_te1, y_tr1, y_te1 = train_test_split(iris_data, iris_label, test_size = 0.2, stratify = iris_label, random_state = 0)

dtc1 = DecisionTreeClassifier(random_state = 0)   # criterion='gini', max_depth=None 등의 옵션 있음
dtc1.fit(X_tr1, y_tr1)

y_te_pred1 = dtc1.predict(X_te1)

print(classification_report(y_te1, y_te_pred1))

# 0.2, 0.4 로 테스트 사이즈 조정하니 아까보다는 낮아짐!

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      1.00      0.95        10
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



### 사이킷런 코드 형식
- sklearn.pipeline 방식대로 작성하는 것을 강력히 권고
    + 공식문서에서도 매우 권장
    + 빅분기 머신러닝파트에서 이 방식대로 달달 외워 적으면 점수 어지간히 나옴(최소 30점 / 40점)
    + https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline

### Model Selection 모듈 소개

In [ ]:
# 0.3으로 해봄
X_tr1, X_te1, y_tr1, y_te1 = train_test_split(iris_data, iris_label, test_size = 0.3, stratify = iris_label, random_state = 0)

dtc1 = DecisionTreeClassifier(random_state = 0)
dtc1.fit(X_tr1, y_tr1)

y_te_pred1 = dtc1.predict(X_te1)

print(classification_report(y_te1, y_te_pred1))
print('예측 정확도:',accuracy_score(y_te1, y_te_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.94      1.00      0.97        15
           2       1.00      0.93      0.97        15

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

예측 정확도: 0.9777777777777777


#### K-폴드 교차 검증
- k = 10의 경우, 10번의 모델 학습
    + 훈련데이터와 검증데이터의 샘플은 각각 다름
    + 평가 5번, 평균을 뽑는 것이 목적

In [ ]:
# 개념만 이해. 실제 코드 작성 방식과는 조금 다를 수 있음

In [ ]:
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성.
kfold = KFold(n_splits=5)    # 층화추출 하려면 StratifiedKFold 사용
cv_accuracy = []
print('붓꽃 데이터 세트 크기:',features.shape[0])

붓꽃 데이터 세트 크기: 150


In [ ]:
n_iter = 0
# KFold객체의 split( ) 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index  in kfold.split(features):
    # kfold.split( )으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    #학습 및 예측
    dt_clf.fit(X_train , y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    # 반복 시 마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test,pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
          .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
    cv_accuracy.append(accuracy)

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도 :1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 :0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 :0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 :0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 :0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


#### StratifiedKFold (층화추출)

In [ ]:
# 층화추출 방식으로 데이터셋 분리 -> 모든 레이블에 대해 분리 일정하게 이루어짐.
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train= iris_df['label'].iloc[train_index]
    label_test= iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


In [ ]:
dt_clf = DecisionTreeClassifier(random_state=156)
skfold = StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]
# StratifiedKFold의 split( ) 호출시 반드시 레이블 데이터 셋도 추가 입력 필요
for train_index, test_index  in skfold.split(features, label):
    # split( )으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    #학습 및 예측
    dt_clf.fit(X_train , y_train)
    pred = dt_clf.predict(X_test)
    # 반복 시 마다 정확도 측정
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
          .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
    cv_accuracy.append(accuracy)

# 교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도:', np.round(np.mean(cv_accuracy), 4))


#1 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 :0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9667
